name: API TEST

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [8, 10, 12]
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies and run test
        run: |
          npm install
          npm run test     
      