name: API TEST

on: [push]

jobs:
  test:
    name: Run Unit Test
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Install dependencies and run test
        run: |
          npm install
          npm run test     
      